### ISSUE TITLE
Results if user not found

### ISSUE THREAD

**Issue by pilz** [JavaDogs/cws#55] opened 2019-05-24 15:22 UTC
```
def test_delete_member():
    data = pycws.fetch_members(URL, 'admin', 'admin', 'test_user')
    assert len(data['members']) == 1

    data = pycws.delete_member(URL, 'admin', 'admin', 'test_user')
    assert data["returnCode"] == 200

    data = pycws.fetch_members(URL, 'admin', 'admin', 'test_user')
    assert len(data['members']) == 0
```
The above test finds test_user, deletes it and wants to check if the user is now gone. But the len of the members list is 45, all users are returned instead of 0.

**Comment by knjensen** [comment] 2019-06-05 11:38
Cannot reproduce, closing.

**Closed by knjensen** 2019-06-05 11:38 UTC
Labels: bug
